version: "3"

services:
  hbase-master:
    image: blueskyareahm/hbase-base:2.1.3
    command: master
    platform: "linux/amd64"
    ports:
      - 16000:16000
      - 16010:16010

  hbase-regionserver:
    image: blueskyareahm/hbase-base:2.1.3
    command: regionserver
    platform: "linux/amd64"
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301

  zookeeper:
    image: blueskyareahm/hbase-zookeeper:3.4.13
    platform: "linux/amd64"
    ports:
      - 2181:2181

  jupyter:                                                                                                                                                                                                
    container_name: jupyter
    build:
      context: ./HBase/jupyter-notebook
    restart: always
    ports:
      - 8888:8888
    user: root
    volumes:
      - ./:/home/jovyan
    command: ["start.sh", "jupyter", "lab", "--NotebookApp.token=''"]
